version: '3'
services:
  db:
    image: postgres
    container_name: webshop-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db


